### ISSUE TITLE
Package not found in npm

### ISSUE THREAD

**Issue by cjtraverso** [jonschlinkert/delete#6]
Hi, when I tried to install **delete** through npm it returns 404 Not Found
URL: https://registry.npmjs.org/delete/-/delete-1.1.0.tgz

Do you know if this package has been deleted from npm?
Thanks in advance!

**Comment by doowb** [comment]
Thanks for opening the issue. I've notified NPM and it looks like they are already aware of the problem.

**Comment by cjtraverso** [comment]
Great! Thanks!

**Comment by cjtraverso** [comment]
I'll close this issue since it is not a problem in the repo.
Thanks a lot!

**Comment by doowb** [comment]
Thanks! It looks like the latest version of `delete` has been restored and they're working on the other versions. You can see the NPM status here: https://status.npmjs.org/incidents/36j9bnllqtnj
